name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        ruby: ["3.1", "3.2", "3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake data:prepare
      - run: bundle exec parallel_rspec spec/
